export default {
  brandSub: 'Driver Finder',
  navHome: 'Home', navMap: 'Map', navDriverList: 'Driver List',
  navServices: 'Services', navAbout: 'About', navContact: 'Contact',
  navFaq: 'FAQ', navUsers: 'Users', navProfile: 'Profile',
  callNow: '📞 Call Now',
  heroEyebrow: "Naypyitaw's Verified Driver Network",
  heroTitleHtml: "Reliable Rides, <em>Every Route,</em><br>Every Corner of Naypyitaw",
  heroSub: "Pick your route, see exactly which licensed driver covers it, and call them directly — no accounts, no waiting, no guesswork.",
  heroBtnFind: 'Find a Driver Now',
  heroBtnDispatch: '📞 Speak to Dispatch',
  trustHubs: 'Pickup Hubs', trustDrivers: 'Licensed Drivers',
  trustDispatch: 'Dispatch Line', trustRating: 'Avg. Fleet Rating',
  whyEyebrow: 'Why Riders Trust Us',
  whyTitle: 'Built for safety, transparency & speed',
  whySub: 'Every driver on Wayz is tied to a fixed base and a verified set of routes — so you always know who is coming, and exactly what it costs.',
  why1Title: 'Detailed Driver Profiles', why1Sub: 'View completed trips, and vehicle details beforehand to choose the right person for your ride.',
  why2Title: 'Flexible Vehicle Choices', why2Sub: 'Choose the right vehicle to match your trip, group size, and budget.',
  why3Title: 'Background Checked Drivers', why3Sub: 'All drivers are verified and background-checked to ensure passenger safety.',
  why4Title: 'Direct Contact', why4Sub: 'Every driver card shows a direct phone number — call and confirm your ride in seconds, no middlemen.',
  driversEyebrow: 'Route-Matched Drivers',
  driversTitle: 'Find Your Driver',
  driversSub: "Choose your pickup and destination — from a dropdown or straight off the map — and we will match you with the nearest available drivers.",
  planRouteTitle: 'Plan Your Route',
  planRouteSub: 'Pickup and destination share the same list of locations. Choosing one removes it from the other list automatically.',
  pickupLabel: 'Pickup Location', pickupLbl: 'Pickup',
  destLabel: 'Destination', destLbl: 'Destination',
  useMyLocation: '📍 Use my location',
  hubTag: 'Hub',
  selectPickup: 'Select pickup location',
  selectPickupFirst: 'Select pickup location first',
  selectDestination: 'Select destination',
  findDriversBtn: 'Find Drivers',
  routeMeter: 'Route Meter', distanceLbl: 'Distance', durationLbl: 'Duration',
  mapLoadingLbl: 'Loading map…',
  legendHub: 'Hub', legendSpot: 'Spot', legendPickup: 'Pickup', legendDest: 'Destination',
  pickupSetToast: 'Pickup set to',
  destSetToast: 'Destination set to',
  emptyChooseTitle: 'Choose a pickup location and destination',
  emptyChooseSub: 'Available drivers depend on your route — pick both ends on the map or from the dropdowns above.',
  noDriversTitle: 'No drivers cover this exact route yet',
  noDriversSubA: 'No driver based at', noDriversSubB: 'currently runs to',
  noDriversSubC: 'Our dispatch team can still help you find a ride.',
  noExactRouteNote: 'No driver has this exact route on file — here are the drivers based nearest your pickup point. Call to confirm they can take you there.',
  callDispatch: 'Call Dispatch',
  callBtnPrefix: 'Call', callBtnSuffix: 'Now',
  rosterEyebrow: 'Full Fleet Roster', rosterTitle: 'Driver List',
  rosterSub: 'Browse every licensed Wayz driver. Search by name or by vehicle type to find exactly who you are looking for.',
  searchFleetTitle: 'Search the Fleet',
  searchFleetSub: 'Type a driver name (e.g. "Kyaw") or a vehicle type (e.g. "Avatar EV") — results update as you type.',
  rosterSearchPlaceholder: 'Search by driver name or vehicle type…',
  allVehicleTypes: 'All vehicle types',
  showingAll: 'Showing all', showing: 'Showing', of: 'of', driversWord: 'drivers',
  servicesEyebrow: 'Our Service',
  servicesTitle: 'City Tour — Naypyitaw, Myanmar',
  servicesSub: 'One focused service, done properly: guided rides through the capital landmarks with drivers who know every route.',
  featuredRoute: 'Featured Route',
  cityTourTitle: 'Guided City Tour of Naypyitaw',
  cityTourSub: 'Ride from Wayz Campus Hub out to the Uppatasanti Pagoda and other landmarks with a knowledgeable local driver. Fixed base, fixed route, transparent fare — every time.',
  viewOnMap: 'View on Map',
  aboutEyebrow: 'About Wayz Transportation',
  aboutTitle: 'A driver network built on accountability',
  aboutP1: 'Wayz Transportation connects riders across Naypyitaw with a fixed roster of licensed drivers — each tied to a real base location, a real vehicle, and a real set of routes they have committed to serving.',
  aboutP2: 'There is no app to install and no account to create. You search a route, see who covers it, and call them directly to confirm your ride.',
  hl1Title: 'Verified Base Locations', hl1Sub: 'Every driver operates from one of 9 fixed hubs across the city.',
  hl2Title: '24/7 Dispatch', hl2Sub: 'Call the main line any time and we will route you to a driver.',
  hl3Title: 'Route Transparency', hl3Sub: 'You only see drivers who genuinely serve your destination.',
  hl4Title: 'Direct Contact', hl4Sub: 'Every driver phone number is right there on their card.',
  contactTitle: 'Get In Touch',
  callUs: 'Call Us', callUsSub: '+95 966 450 054 — Available 24/7',
  emailUs: 'Email Us', headOffice: 'Head Office',
  headOfficeSub: 'Wayz Campus Hub, Naypyitaw, Myanmar',
  hours: 'Hours', hoursSub: '24 Hours / 7 Days — Always Open',
  emailNow: '✉️ Email Now',
  yourName: 'Your Name', yourEmail: 'Your Email',
  subject: 'Subject', yourMessage: 'Your Message',
  sendMessage: 'Send Message',
  footerBottomHtml: '&copy; 2026 Wayz Transportation, Naypyitaw. All rights reserved.',
  geoUnsupported: 'Geolocation is not supported on this device.',
  findingNearestHub: 'Finding your nearest pickup hub…',
  nearestHubToast: 'Nearest hub:',
  geoDenied: 'Could not access your location. Please select a hub manually.',
  selectBoth: 'Please select both a pickup hub and a destination.',
  messageSent: 'Message sent! Our team will get back to you shortly.',
  choosePickupMode: 'Pickup mode active — click on the map',
  chooseDestMode: 'Destination mode active — click on the map',
  faqTitle: 'Frequently Asked Questions',
  faqSub: 'Common questions about Wayz Transportation services',
  usersTitle: 'User Management',
  usersSub: 'Manage registered users and their profiles',
  profileTitle: 'Your Profile',
  profileSub: 'Manage your personal information and preferences'
}
