export const LOCATIONS = [
  { id:"ocean", name:"Ocean Super Center Hub (Ottarathiri)", lat:19.817165195371956, lng:96.15440628725972, base:true },
  { id:"train-station", name:"Naypyidaw Central Railway Station", lat:19.85, lng:96.1961, base:true },
  { id:"museum", name:"National Museum & Gems Commercial Area", lat:19.734, lng:96.1119, base:true },
  { id:"airport", name:"Naypyidaw International Airport (NYT)", lat:19.6205, lng:96.1988, base:true },
  { id:"thapyaykone", name:"Thabyegone Market Hub (Zabuthiri)", lat:19.7423, lng:96.1158, base:true },
  { id:"university", name:"NSPU – Naypyitaw State Polytechnic University", lat:19.848515, lng:96.159470, base:true },
  { id:"myoma", name:"Myoma Market", lat:19.739, lng:96.136, base:true },
  { id:"junction", name:"Junction Supermarket", lat:19.7562, lng:96.0827, base:true },
  { id:"hospital", name:"Naypyidaw General Hospital", lat:19.7126, lng:96.1017, base:true },
  { id:"yau", name:"Yezin Agricultural University (YAU)", lat:19.8333, lng:96.2667, base:false },
  { id:"forestry-uni", name:"University of Forestry & Environmental Science", lat:19.8375, lng:96.2642, base:false },
  { id:"hypermarket", name:"Capital Hypermarket Naypyidaw", lat:19.7314, lng:96.0955, base:false },
  { id:"pyinmana-market", name:"Pyinmana Central Market Zone", lat:19.7337, lng:96.2057, base:false },
  { id:"parliament", name:"Parliament Complex (Hluttaw Building)", lat:19.761, lng:96.0792, base:false },
  { id:"palace", name:"Presidential Palace Zone", lat:19.771, lng:96.103, base:false },
  { id:"transport-ministry", name:"Ministry of Transport & Communications", lat:19.7891, lng:96.134, base:false },
  { id:"education-ministry", name:"Ministry of Education (Office No. 13)", lat:19.7876, lng:96.1368, base:false },
  { id:"foreign-ministry", name:"Ministry of Foreign Affairs", lat:19.8164, lng:96.1432, base:false },
  { id:"pagoda", name:"Uppatasanti Pagoda", lat:19.7711, lng:96.183, base:false },
  { id:"zoological-gardens", name:"Naypyidaw Zoological Gardens", lat:19.7825, lng:96.1350, base:false },
  { id:"safari-park", name:"Naypyidaw Safari Park", lat:19.7685, lng:96.1320, base:false },
  { id:"gems-museum", name:"Myanmar Gems Museum", lat:19.7340, lng:96.1119, base:false },
  { id:"landmark-garden", name:"National Landmark Garden", lat:19.7580, lng:96.0970, base:false },
  { id:"water-fountain-garden", name:"Water Fountain Garden", lat:19.7630, lng:96.1030, base:false },
  { id:"parliament-viewpoint", name:"Parliament Building (Viewpoint)", lat:19.7610, lng:96.0792, base:false },
  { id:"yan-aung-myin-pagoda", name:"Yan Aung Myin Pagoda", lat:19.7560, lng:96.1490, base:false }
]

export const DRIVERS = [
  { id:1, name:"Ko Nyan Lin Aung", base:"ocean", vehicle:"EV:Leapmotor T-03", carNumber:"NPW-HH/2278", rating:4.7, reviews:181, avatar:"👨‍💼", phone:"+95 9954777496", experience:"8 years" },
  { id:2, name:"Ko Toe Wai", base:"ocean", vehicle:"Toyota Probox", carNumber:"NPW-BB/1560", rating:4.9, reviews:187, avatar:"🤵‍♂️", phone:"+95 9782220250", experience:"7 years" },
  { id:3, name:"Ko Htet Oo", base:"ocean", vehicle:"Toyota Probox", carNumber:"MDY-6B/2895", rating:4.7, reviews:104, avatar:"👨‍💼", phone:"+95 9266669650", experience:"6 years" },
  { id:4, name:"U Banyar Naing", base:"ocean", vehicle:"Honda Insight", carNumber:"NPW-6P/5152", rating:4.8, reviews:157, avatar:"🤵‍♂️", phone:"+95 9782220250", experience:"14 years" },
  { id:5, name:"Ko Htun Oo", base:"train-station", vehicle:"Ceraus", carNumber:"YGN-5F/2086", rating:5.0, reviews:154, avatar:"👨‍💼", phone:"+95 9266669650", experience:"11 years" },
  { id:6, name:"Pobba EV{pls, book early}", base:"train-station", vehicle:"EV:Leapmotor T-03", carNumber:"NPW-HH/4828", rating:4.6, reviews:219, avatar:"🤵‍♂️", phone:"+95 9442806400", experience:"12 years" },
  { id:7, name:"Ko Thura Aung", base:"train-station", vehicle:"hiace(for multiple people)", carNumber:"YGN-6C/6816", rating:4.9, reviews:110, avatar:"👨‍💼", phone:"+95 9782220250", experience:"4 years" },
  { id:8, name:"U Min Khant", base:"train-station", vehicle:"light Truck(for multiple people)", carNumber:"YGN-8D/7677", rating:4.9, reviews:205, avatar:"🤵‍♂️", phone:"+95 926669650", experience:"4 years" },
  { id:9, name:"U Lay Thein", base:"museum", vehicle:"Avatar EV", carNumber:"MDY-HH/1519", rating:4.5, reviews:150, avatar:"👨‍💼", phone:"+95 9683111302", experience:"7 years" },
  { id:10, name:"Ko Kyi Thein", base:"museum", vehicle:"EV:Leapmotor T-03", carNumber:"YGN-HH/2926", rating:4.9, reviews:103, avatar:"🤵‍♂️", phone:"+95 9898124856", experience:"13 years" },
  { id:11, name:"Ko Zaw Myo", base:"museum", vehicle:"Honda Fit", carNumber:"NPW-9P/1146", rating:4.7, reviews:115, avatar:"👨‍💼", phone:"+95 9880610774", experience:"3 years" },
  { id:12, name:"U Tin Oo", base:"museum", vehicle:"Toyota Camry", carNumber:"MDY-9D/8906", rating:4.6, reviews:206, avatar:"🤵‍♂️", phone:"+95 9768102138", experience:"7 years" },
  { id:13, name:"Ko Yan Naing", base:"airport", vehicle:"Toyota Corolla", carNumber:"YGN-8F/5075", rating:5.0, reviews:110, avatar:"👨‍💼", phone:"+95 9783419696", experience:"5 years" },
  { id:14, name:"U Tat Lu", base:"airport", vehicle:"Suzuki Swift", carNumber:"MDY-6K/4979", rating:4.9, reviews:151, avatar:"🤵‍♂️", phone:"+95 9682609307", experience:"7 years" },
  { id:15, name:"Ko Htut Khaung", base:"airport", vehicle:"Avatar EV", carNumber:"YGN-HH/2774", rating:4.9, reviews:184, avatar:"👨‍💼", phone:"+95 9665185474", experience:"7 years" },
  { id:16, name:"U Htun Kyaing", base:"airport", vehicle:"Toyota Hiace", carNumber:"NPW-6P/7979", rating:4.6, reviews:143, avatar:"🤵‍♂️", phone:"+95 9673977058", experience:"14 years" },
  { id:17, name:"U Nay Myo", base:"thapyaykone", vehicle:"Honda Fit", carNumber:"NPW-7D/9086", rating:4.9, reviews:92, avatar:"👨‍💼", phone:"+95 9441464646", experience:"4 years" },
  { id:18, name:"U Aye Naing Win", base:"thapyaykone", vehicle:"Toyota Camry", carNumber:"", rating:4.6, reviews:194, avatar:"🤵‍♂️", phone:"+95 9976499416", experience:"12 years" },
  { id:19, name:"Pyae Sone", base:"thapyaykone", vehicle:"Toyota Corolla", carNumber:"", rating:4.9, reviews:210, avatar:"👨‍💼", phone:"+95 9697130685", experience:"6 years" },
  { id:20, name:"Bhone Myint", base:"thapyaykone", vehicle:"Suzuki Swift", carNumber:"", rating:5.0, reviews:174, avatar:"🤵‍♂️", phone:"+95 9791181101", experience:"3 years" },
  { id:21, name:"Mg Mg", base:"university", vehicle:"Avatar EV", carNumber:"", rating:4.5, reviews:201, avatar:"👨‍💼", phone:"+95 966 555 021", experience:"3 years" },
  { id:22, name:"Kyi Kyi", base:"university", vehicle:"Toyota Hiace", carNumber:"", rating:4.6, reviews:197, avatar:"👩‍💼", phone:"+95 966 555 022", experience:"13 years" },
  { id:23, name:"Htet Aung", base:"university", vehicle:"Honda Fit", carNumber:"", rating:4.6, reviews:111, avatar:"👨‍💼", phone:"+95 966 555 023", experience:"7 years" },
  { id:24, name:"Phyo May", base:"university", vehicle:"Toyota Camry", carNumber:"", rating:4.7, reviews:139, avatar:"👩‍💼", phone:"+95 966 555 024", experience:"14 years" },
  { id:25, name:"Tun Tun", base:"myoma", vehicle:"Toyota Corolla", carNumber:"", rating:4.7, reviews:208, avatar:"👨‍💼", phone:"+95 966 555 025", experience:"13 years" },
  { id:26, name:"Yin Yin", base:"myoma", vehicle:"Suzuki Swift", carNumber:"", rating:4.7, reviews:151, avatar:"👩‍💼", phone:"+95 966 555 026", experience:"7 years" },
  { id:27, name:"Zayar Win", base:"myoma", vehicle:"Avatar EV", carNumber:"", rating:4.7, reviews:209, avatar:"👨‍💼", phone:"+95 966 555 027", experience:"9 years" },
  { id:28, name:"Nandar Hlaing", base:"myoma", vehicle:"Toyota Hiace", carNumber:"", rating:4.6, reviews:201, avatar:"👩‍💼", phone:"+95 966 555 028", experience:"10 years" },
  { id:29, name:"Thiha Soe", base:"junction", vehicle:"Honda Fit", carNumber:"", rating:4.9, reviews:136, avatar:"👨‍💼", phone:"+95 966 555 029", experience:"3 years" },
  { id:30, name:"Thaw Thaw", base:"junction", vehicle:"Toyota Camry", carNumber:"", rating:4.6, reviews:107, avatar:"👩‍💼", phone:"+95 966 555 030", experience:"13 years" },
  { id:31, name:"Ko Ko", base:"junction", vehicle:"Toyota Corolla", carNumber:"", rating:4.6, reviews:119, avatar:"👨‍💼", phone:"+95 966 555 031", experience:"5 years" },
  { id:32, name:"Wai Wai", base:"junction", vehicle:"Suzuki Swift", carNumber:"", rating:4.8, reviews:120, avatar:"👩‍💼", phone:"+95 966 555 032", experience:"12 years" },
  { id:33, name:"Kyaw Kyaw", base:"hospital", vehicle:"Avatar EV", carNumber:"", rating:4.6, reviews:135, avatar:"👨‍💼", phone:"+95 966 555 033", experience:"14 years" },
  { id:34, name:"Zin Zin", base:"hospital", vehicle:"Toyota Hiace", carNumber:"", rating:4.5, reviews:173, avatar:"👩‍💼", phone:"+95 966 555 034", experience:"5 years" },
  { id:35, name:"Aung Aung", base:"hospital", vehicle:"Honda Fit", carNumber:"", rating:4.8, reviews:151, avatar:"👨‍💼", phone:"+95 966 555 035", experience:"14 years" },
  { id:36, name:"Lae Lae", base:"hospital", vehicle:"Toyota Camry", carNumber:"", rating:5.0, reviews:174, avatar:"👩‍💼", phone:"+95 966 555 036", experience:"8 years" },
  { id:37, name:"Zayar Htet", base:"ocean", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:137, avatar:"👨‍💼", phone:"+95 966 555 037", experience:"5 years" },
  { id:38, name:"Nilar Win", base:"train-station", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:138, avatar:"👩‍💼", phone:"+95 966 555 038", experience:"6 years" },
  { id:39, name:"Aung Kyaw", base:"museum", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:139, avatar:"👨‍💼", phone:"+95 966 555 039", experience:"7 years" },
  { id:40, name:"Sandar Oo", base:"airport", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:140, avatar:"👩‍💼", phone:"+95 966 555 040", experience:"8 years" },
  { id:41, name:"Thet Naing", base:"thapyaykone", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:141, avatar:"👨‍💼", phone:"+95 966 555 041", experience:"9 years" },
  { id:42, name:"Wut Yee", base:"university", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:142, avatar:"👩‍💼", phone:"+95 966 555 042", experience:"10 years" },
  { id:43, name:"Kaung Sat", base:"myoma", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:143, avatar:"👨‍💼", phone:"+95 966 555 043", experience:"11 years" },
  { id:44, name:"Ei Ei Phyo", base:"junction", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:144, avatar:"👩‍💼", phone:"+95 966 555 044", experience:"12 years" },
  { id:45, name:"Myo Min", base:"hospital", vehicle:"OE Way", carNumber:"", rating:4.8, reviews:145, avatar:"👨‍💼", phone:"+95 966 555 045", experience:"13 years" }
]

export const DRIVER_ROUTES = {
  1: ["airport","forestry-uni","hospital","pyinmana-market"],
  2: ["junction","train-station","foreign-ministry","yau","palace","hospital"],
  3: ["transport-ministry","yau","train-station","airport","palace","pyinmana-market"],
  4: ["university","education-ministry","junction","forestry-uni","transport-ministry","foreign-ministry"],
  5: ["foreign-ministry","forestry-uni","palace","pyinmana-market","education-ministry","transport-ministry"],
  6: ["museum","thapyaykone","education-ministry","foreign-ministry"],
  7: ["ocean","thapyaykone","myoma","palace","parliament"],
  8: ["pyinmana-market","education-ministry","university","museum","junction"],
  9: ["myoma","pagoda","train-station","airport","parliament"],
  10: ["palace","ocean","university","airport"],
  11: ["pyinmana-market","university","myoma","train-station","foreign-ministry"],
  12: ["train-station","hospital","airport","parliament"],
  13: ["transport-ministry","yau","education-ministry","foreign-ministry","university","myoma"],
  14: ["thapyaykone","palace","hypermarket","museum"],
  15: ["junction","thapyaykone","pagoda","foreign-ministry","palace"],
  16: ["thapyaykone","transport-ministry","forestry-uni","myoma","pagoda","museum"],
  17: ["education-ministry","airport","foreign-ministry","transport-ministry","hospital","parliament"],
  18: ["pagoda","airport","hypermarket","forestry-uni","train-station"],
  19: ["foreign-ministry","yau","train-station","myoma","forestry-uni","hospital"],
  20: ["museum","hypermarket","pyinmana-market","parliament","hospital"],
  21: ["ocean","transport-ministry","yau","parliament","airport","museum"],
  22: ["pagoda","hypermarket","museum","train-station","hospital","palace"],
  23: ["pyinmana-market","myoma","hospital","yau","train-station"],
  24: ["yau","palace","foreign-ministry","hospital"],
  25: ["thapyaykone","train-station","ocean","education-ministry","pagoda","airport"],
  26: ["hospital","pyinmana-market","ocean","palace","junction"],
  27: ["thapyaykone","yau","pagoda","airport","university"],
  28: ["yau","train-station","pyinmana-market","forestry-uni"],
  29: ["train-station","palace","museum","pyinmana-market","transport-ministry"],
  30: ["myoma","yau","pyinmana-market","pagoda","thapyaykone"],
  31: ["yau","parliament","museum","education-ministry","hospital","university"],
  32: ["thapyaykone","museum","parliament","forestry-uni","foreign-ministry","airport"],
  33: ["ocean","hypermarket","palace","parliament","transport-ministry"],
  34: ["foreign-ministry","airport","museum","transport-ministry","junction"],
  35: ["palace","foreign-ministry","forestry-uni","yau","museum"],
  36: ["ocean","education-ministry","pagoda","junction"],
  37: ["ocean","train-station","museum","airport","thapyaykone","university","myoma","junction","hospital","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"],
  38: ["ocean","museum","airport","thapyaykone","university","myoma","junction","hospital","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"],
  39: ["ocean","train-station","airport","thapyaykone","university","myoma","junction","hospital","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"],
  40: ["ocean","train-station","museum","thapyaykone","university","myoma","junction","hospital","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"],
  41: ["ocean","train-station","museum","airport","university","myoma","junction","hospital","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"],
  42: ["ocean","train-station","museum","airport","thapyaykone","myoma","junction","hospital","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"],
  43: ["ocean","train-station","museum","airport","thapyaykone","university","junction","hospital","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"],
  44: ["ocean","train-station","museum","airport","thapyaykone","university","myoma","hospital","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"],
  45: ["ocean","train-station","museum","airport","thapyaykone","university","myoma","junction","yau","forestry-uni","hypermarket","pyinmana-market","parliament","palace","transport-ministry","education-ministry","foreign-ministry","pagoda"]
}
